name: ipd_getx_project_backup
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  barcode_scan_fix: ^1.0.2
  fl_chart: 0.40.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  get_cli: ^1.6.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - Images/
  uses-material-design: true

